### ISSUE TITLE
Hydration failed because the initial UI does not match what was rendered on the server

### ISSUE THREAD

**Issue by MahmadSharaf** [saleor/react-storefront#176]
### Summary

After installing the Docker version and running the React Storefront. It displays these errors.

![image](https://user-images.githubusercontent.com/36701447/162439545-9bc399ba-dc71-4337-bb43-0d6f04abc0f2.png)

### Steps to reproduce

1. Follow the instructions [here ](https://docs.saleor.io/docs/3.x/developer/installation) to install Saleor.
2. Run the services using `docker-compose up`
3. Open http://localhost:3001

### What OS are you using?

Windows

### Your `next.config.js` file

```js
const withBundleAnalyzer = require("@next/bundle-analyzer")({
  enabled: process.env.ANALYZE === "true",
});

const apiURL = new URL(process.env.NEXT_PUBLIC_API_URI);

module.exports = withBundleAnalyzer({
  reactStrictMode: true,
  swcMinify: true,
  images: {
    domains: [apiURL.hostname, "img.youtube.com"],
    formats: ["image/avif", "image/webp"],
  },
  async redirects() {
    return [
      {
        source: "/",
        // TODO: Investigate why constants from project cannot be imported
        // User should be redirected to the defaults defined in @lib/regions
        destination: "/default-channel/en-US",
        permanent: false,
      },
    ];
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          {
            key: "x-content-type-options",
            value: "nosniff",
          },
          { key: "x-xss-protection", value: "1" },
          { key: "x-frame-options", value: "DENY" },
          {
            key: "strict-transport-security",
            value: "max-age=31536000; includeSubDomains",
          },
        ],
      },
    ];
  },
  experimental: {
    reactRoot: true,
  },
});
```

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

**Comment by MahmadSharaf** [comment]
It is fixed by creating a channel and set its slug to "default-channel"

**Comment by festelle** [comment]
I've been having the same problem, i tried creating a channel with the slug "default-channel" but it still isn't working.
This is my channel:
<img width="1265" alt="Captura de Pantalla 2022-06-05 a la(s) 23 20 17" src="https://user-images.githubusercontent.com/62019727/172089199-cfc8efc6-dff5-4ed2-83f6-3abaa282c642.png">

And this is the error that is showing:
<img width="1383" alt="Captura de Pantalla 2022-06-05 a la(s) 23 20 41" src="https://user-images.githubusercontent.com/62019727/172089256-779de630-8c27-413a-8de5-f25c543133c5.png">

I've been searching for solutions but haven't found anything that works, I would greatly appreciate any type of guidance!

**Comment by MahmadSharaf** [comment]
Yes, you also need to create a Navigation page. I am not sure the need of the below, but worth trying:
- A catalog
- A Product Type
- Fill your site info

**Comment by festelle** [comment]
I did everything that you mentioned and now is working, Thank you!
