### ISSUE TITLE
Issues with Cart Address Validation

### ISSUE THREAD

**Issue by matteius** [saleor/react-storefront#205]
### Summary

Deployed a new saleor, dashboard and react-storefront container to my new site and spent some days configuring and understanding whats going on.  Finally got past some build and  configuration issues and now I can add items to the cart and its the checkout checkout process address validation that is broken.  Here are my notes:

1. Saving a Billing Address: Silently fails and clears out the form data
2. The phone number has to have a + prefix in front of it, so for example +1206555555 and not 1206555555, or 206555555 or any other attempt at formatting that with out the +1 country code.  No validation errors on screen, address clears,
3. The form data in the network tab defaults the country to PL so I edited it in  my fork to default to US.
4. Despite changing the country code the backend continues to fail to validate the zip code -- it seems the form needs to collect the `country_area` field on the form which is the users state.  I haven't tried adding this to see what the next issue might be, yet.

As such I cannot get past adding the Billing address to the cart and the end user has no idea about why the address is clearing after each attempt, without debugging the application.

### Steps to reproduce

Here is a demo, visit: https://mattscoinage.com/default-channel/en-US/products/test-stripe
add the product to cart and attempt to start checkout.

### A link to a reproduction repository

https://github.com/matteius/react-storefront

### What OS are you using?

Linux

### Your `next.config.js` file

# This is the default next.config.js file
<details>
  <summary>`next.config.js`</summary>

```
const withBundleAnalyzer = require("@next/bundle-analyzer")({
  enabled: process.env.ANALYZE === "true",
});

const apiURL = new URL(process.env.NEXT_PUBLIC_API_URI);
const allowedImageDomains = process.env.NEXT_PUBLIC_ALLOWED_IMAGE_DOMAINS
  ? process.env.NEXT_PUBLIC_ALLOWED_IMAGE_DOMAINS.split(",")
  : [];
const imageConversionFormats = process.env.NEXT_PUBLIC_IMAGE_CONVERSION_FORMATS
  ? process.env.NEXT_PUBLIC_IMAGE_CONVERSION_FORMATS.split(",")
  : [];

module.exports = withBundleAnalyzer({
  reactStrictMode: true,
  swcMinify: true,
  images: {
    domains: [apiURL.hostname, ...allowedImageDomains],
    formats: imageConversionFormats,
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          {
            key: "x-content-type-options",
            value: "nosniff",
          },
          { key: "x-xss-protection", value: "1" },
          { key: "x-frame-options", value: "DENY" },
          {
            key: "strict-transport-security",
            value: "max-age=31536000; includeSubDomains",
          },
        ],
      },
    ];
  },
  experimental: {
    reactRoot: true,
  },
});

```

</details>

### Builds logs (or link to your logs)

```
FROM docker.io/node:16
WORKDIR /app
RUN npm install -g pnpm@6.32.11
COPY . .
RUN pnpm i

ARG NEXT_PUBLIC_API_URI
ARG NEXT_PUBLIC_DEFAULT_CHANNEL
ARG NEXT_PUBLIC_VERCEL_URL

ENV NEXT_PUBLIC_API_URI ${NEXT_PUBLIC_API_URI:-https://api.mattscoinage.com/graphql/}
ENV NEXT_PUBLIC_DEFAULT_CHANNEL ${NEXT_PUBLIC_DEFAULT_CHANNEL:-default-channel}

# export failed with this:
# Error: i18n support is not compatible with next export. See here for more info on deploying: https://nextjs.org/docs/deployment
# RUN pnpm run export

# This is to prevent this error:
#   http://mynewreactstorefront.example.com/_next/image?url=http%3A%2F%2Fmysaleorapi.example.com%2Fmedia%2Fproducts%2Fsaleordemoproduct_cl_boot07_1.png&w=828&q=75
#   400 Bad Request
#   data:text/plain,"url" parameter is not allowed
# which seems to come from this Next.js source file:
#  https://github.com/vercel/next.js/blob/canary/packages/next/server/image-optimizer.ts
#if (!domains.includes(hrefParsed.hostname)) {
#  res.statusCode = 400
#  res.end('"url" parameter is not allowed')
#  return { finished: true }
#}
# RUN sed -i 's/"img.youtube.com"/"img.youtube.com", "mysaleorapi.example.com"/g' next.config.js

# Then as an alternative to the failed "pnpm run export" attempt, we will directly
# run the Node application in production mode, exposing its default port 3000.
# see https://nextjs.org/docs/api-reference/cli#production
# see https://github.com/saleor/react-storefront/issues/84#issuecomment-966874104
expose 3010
RUN pnpm run build
CMD PORT=3010 pnpm run start
```

**Comment by matteius** [comment]
I've made some improvements in my branch for US address check out, fighting with the stripe integration next as the checkout simply doesn't show any errors or order confirmation when I try to check out.

**Comment by reachkrishnaraj** [comment]
Following. Stuck on this.

**Comment by matteius** [comment]
No, I am not familiar with it other than reading it's name in another thread that sounded like it was going to be released soon.  Any additional details?

**Comment by wileyknight** [comment]
> No, I am not familiar with it other than reading it's name in another thread that sounded like it was going to be released soon. Any additional details?

I haven't got it to work yet but I have seen it working from the PR previews, it fixes and streamlines the checkout from the storefront. I've been trying to get it configured but haven't made any major headway. Added some issues on it though. Hopefully we can get it working soon.

**Comment by wileyknight** [comment]
I had the same problem with the country code and phone number. I'm just rewriting the field inputs on the post so that it can be entered naturally. I was going to do the same thing you are doing and fixing the issues myself until I saw the checkout.

**Comment by wileyknight** [comment]
I opened a discussion with instructions on how to run the checkout and storefront if you're interested. React-storefront & checkout integration #209

**Comment by matteius** [comment]
@wileyknight I have fixed this is my react-storefront branch -- what advantage would using the separate checkout repository?  It seems like more overhead to me and would require deploying now a 4th docker container to run the site -- I am pretty happy without going in this direction and using the checkout code that is in this repository that I have modified in my fork to fix a few bugs.

**Comment by simon-online** [comment]
Yes the current react-storefront checkout user experience isn't great with strict phone and address validation and no error messages displaying.  It definitely could be better to provide a better testing experience.

However I was able to successfully complete the checkout without modifying the code by providing an international phone number eg. +48123456789 and entering in an address in Poland. eg.

Address:
Tęczowa 7

City:
Wrocław

Postal code:
53-601

**Comment by matteius** [comment]
@simon-online In my fork I added the form validation errors to the output on the screen.   I also changed my defaults to US and added the countryRegion (state) field.  Checkout works, but no organic sales yet.

**Comment by wileyknight** [comment]
@matteius 

This will help with the phone number validation:

Above the return on AddressForm.tsx

```
const phoneFormatHandler = (arg0: any): string => {
  
    const reformatted = `+1${arg0}`;

    if (arg0.slice(0,1) !== "+") {
      if (arg0.slice(1,2) !== "1") {
        return reformatted;
      } 
      return reformatted;
    }
    
    if (arg0.slice(0,1) !== "1") {
      return reformatted;
    } 
    
    return arg0;
  }
```

and in the phone input:
```
{...registerAddress("phone", {
  required: true,
  pattern: /^([+]?[\s0-9]+)?(\d{3}|[(]?[0-9]+[)])?([-]?[\s]?[0-9])+$/i,
  setValueAs: e => phoneFormatHandler(e),
})}
```

Now customers wont have to add the + or the 1 for the phone number to go thru.

**Comment by wileyknight** [comment]
@matteius 

I made that way too complicated... I was testing and realized that this works just but adding

`setValueAs: e => `1${e}`,`

to the input.

**Comment by matteius** [comment]
I think this was fixed recently when I merged upstream into my branch -- I can enter my number with area-code only and it gets saved with the +1 -- the only real issue I am having with the address flow right now is that my form defaults the countryArea (state) field to be United States instead of my billing state -- seems less than ideal, but also wasn't why I opened this issue originally.

**Comment by wileyknight** [comment]
@matteius 

I was still having problems with my form when saving so I made the aforementioned change... I am not using the most updated backend, yet, but this fixed it from the frontend side.

I had the same problems as you with the State and had to make the changes to include countryArea as State to get it working. I am not having trouble with it defaulting to to the country though. It looks like we have the exact same fixes for the country area except your description in translations.ts still says country area. `description: "Country area field label.",` `description: "State field label.",`

Maybe convert that to a selector with options for the abbreviated state names. Amazon is using that type of input, not to say it's the best, but it's familiar.

**Comment by gleniat** [comment]
Why this is closed as completed? I tested this on latest backend+storefront and all the issues OP described are still there.

**Comment by wileyknight** [comment]
This isn't the first time this has happened. Many issues have been closed as completed that have not.

**Comment by timuric** [comment]
@wileyknight @gleniat please use saleor-checkout repo, we are in process of merging both projects, checkout page in this repository would be dropped

**Comment by gleniat** [comment]
I will give it a try. Am I supposed to run 5 separate apps instead of 3? Backend + react-storefront + checkout + checkout-app + dashboard? That seems a bit complicated. Dockerfiles are missing in checkout and checkout-app so I will probably need to create them myself.

`merging both projects` which projects are you going to merge? react-storefront + checkout-app? Thanks!

**Comment by timuric** [comment]
@gleniat None of the front end projects need docker, they are next.js projects and can be easily deployed to Vercel. Dashboard is a react SPA which can be served as a static files. I strongly recommend you not to use docker for local development and specially for production.

I agree that the setup is a bit complicated, but there are good reasons and advantages of separated packages. Storefront is meant to be modified while checkout is quite complex to maintain and can be convenient to upgrade as we ship improvements. 

We provide CLI tool to automate development and deployment process as well as free saleor cloud accounts to run dashboard and backend.

**Comment by matteius** [comment]
What is the difference between checkout and checkout-app?  For those of us not deploying to Vercel, probably those other projects do require Docker or at least that is the most obvious way outside of Vercel, or are they like Dashboard in that they can be deployed as static files?  I think it would be nice, even if they are separate repositories, to be able to include the frontend in a single Docker container running behind a single pnpm server.

**Comment by timuric** [comment]
@matteius checkout app is a saleor app for managing checkout theme and processing payments. Checkout is a static SPA, checkout app is a next js application
